# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='user_friend',
            new_name='bestfriend',
        ),
    ]
